import{test,expect}from"playwright/test";
import{mkdir}from"node:fs/promises";
import{resolve}from"node:path";
const gamePath="/"+encodeURI("콩쥐야_줘때써.html");
const shots=resolve(process.cwd(),"artifacts","quiz-ui-qa");
const desktopSizes=[[1280,720],[1366,768],[1440,900],[1920,1080],[2560,1440]];
const mobileSizes=[[320,568],[360,640],[390,844],[412,915],[768,1024]];
async function openGame(page,training="atomic_number"){await page.goto(`${gamePath}?training=${training}`,{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>globalThis.KongJuiYaGame?.game?.question,{timeout:20000});await expect(page.locator("#questionText")).not.toHaveText("문제를 준비하고 있습니다.")}
async function noHorizontalOverflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy()}
test.use({browserName:"chromium",launchOptions:{executablePath:"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"}});
test("PC 퀴즈는 입력·일시정지·결과 화면을 유지한다",async({page})=>{const errors=[];page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});for(const [width,height] of desktopSizes){await page.setViewportSize({width,height});await openGame(page);await noHorizontalOverflow(page);await expect(page.locator("#visualStage")).toBeVisible();await expect(page.locator("#answerInput")).toBeVisible()}const answer=await page.evaluate(()=>{const q=globalThis.KongJuiYaGame.game.question;return Array.isArray(q.answers)?q.answers[0]:Array.isArray(q.answer)?q.answer[0]:q.answer??q.correctChoice});await page.locator("#answerInput").fill(String(answer));await page.locator("#answerInput").press("Enter");await page.waitForFunction(()=>Number(document.getElementById("scoreValue")?.textContent||0)>0);await page.locator("#ui-pauseButton").click();await page.waitForFunction(()=>globalThis.KongJuiYaGame.game.state.status==="paused");await page.locator("#ui-pauseButton").click();await page.waitForFunction(()=>globalThis.KongJuiYaGame.game.state.status==="running");await page.evaluate(()=>globalThis.KongJuiYaGame.game.over("browser-qa"));await expect(page.locator("#resultPanel")).not.toHaveClass(/hidden/);await mkdir(shots,{recursive:true});await page.setViewportSize({width:1280,height:720});await page.screenshot({path:resolve(shots,"desktop-1280x720.png")});expect(errors).toEqual([])});
test("모바일 퀴즈는 각 viewport에서 키패드와 툴바를 유지한다",async({browser})=>{await mkdir(shots,{recursive:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});await page.addInitScript(()=>localStorage.setItem("kongjuiya-device-mode","mobile"));for(const [width,height] of mobileSizes){await page.setViewportSize({width,height});await openGame(page);await page.waitForSelector("#ui-mobileKeypad:not([hidden])");await expect(page.locator(".game-bottom-toolbar")).toBeVisible();expect(await page.evaluate(()=>{const submit=document.querySelector(".keypad-submit")?.getBoundingClientRect(),toolbar=document.querySelector(".game-bottom-toolbar")?.getBoundingClientRect();return Boolean(submit&&toolbar&&submit.bottom<=toolbar.top+.5)})).toBeTruthy();await expect(page.locator(".jar-wrap")).toBeVisible();await noHorizontalOverflow(page);expect(await page.evaluate(()=>document.documentElement.scrollHeight<=window.innerHeight+1)).toBeTruthy();if(width===320)await page.screenshot({path:resolve(shots,"mobile-320x568.png")});if(width===390)await page.screenshot({path:resolve(shots,"mobile-390x844.png")})}await page.setViewportSize({width:568,height:320});await openGame(page);await expect(page.locator("#ui-mobileKeypad:not([hidden])")).toBeVisible();await noHorizontalOverflow(page);await context.close();expect(errors).toEqual([])});
test("모바일 키패드는 소수점·부호·선택형과 fallback을 전환한다",async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await page.addInitScript(()=>localStorage.setItem("kongjuiya-device-mode","mobile"));const findDescriptor=async(training,check)=>{await openGame(page,training);return page.evaluate(check)};expect(await findDescriptor("atomic_mass",()=>{const g=globalThis.KongJuiYaGame.game;for(let i=0;i<30;i++){if((g.snapshot().questionInput.allowedKeys||[]).includes("."))return true;g.nextQuestion()}return false})).toBeTruthy();await expect(page.locator(".keypad-modifier",{hasText:"."})).toBeVisible();expect(await findDescriptor("ion_charge",()=>{const g=globalThis.KongJuiYaGame.game;for(let i=0;i<30;i++){const d=g.snapshot().questionInput;if(d.inputMode==="signed_numeric_keypad"||(d.allowedKeys||[]).includes("-"))return true;g.nextQuestion()}return false})).toBeTruthy();await expect(page.locator(".keypad-modifier",{hasText:"−"})).toBeVisible();expect(await findDescriptor("redox",()=>{const g=globalThis.KongJuiYaGame.game;for(let i=0;i<30;i++){if((g.snapshot().questionInput.choices||[]).length)return true;g.nextQuestion()}return false})).toBeTruthy();await expect(page.locator(".mobile-keypad.is-choice .keypad-choice")).toHaveCount(2);await openGame(page,"ionic_formula");const descriptor=await page.evaluate(()=>globalThis.KongJuiYaGame.game.snapshot().questionInput);expect(descriptor.inputMode).toBe("formula_keyboard");await expect(page.locator("#answerInput")).toBeVisible();await expect(page.locator("#submitButton")).toBeVisible();await expect(page.locator("#ui-mobileKeypad")).toBeHidden();await context.close()});
test("정보 페이지는 광고 요청 없이 열리고 정적 파일에 접근한다",async({page})=>{const requests=[];page.on("request",request=>{if(/googlesyndication|doubleclick/.test(request.url()))requests.push(request.url())});for(const path of["/about.html","/how-to-play.html","/chemistry-guide.html","/faq.html","/privacy.html","/terms.html","/contact.html","/robots.txt","/sitemap.xml"]){const response=await page.goto(path);expect(response?.status()).toBe(200)}await page.goto("/about.html");expect(await page.evaluate(()=>fetch("/ads.txt.example").then(response=>response.status))).toBe(200);await expect(page.locator("h1")).toBeVisible();await mkdir(shots,{recursive:true});await page.screenshot({path:resolve(shots,"content-about.png")});expect(requests).toEqual([])});
