import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";
import{GAME_TITLE,JAR_THEMES,displayJarName,themeFor}from"../assets/js/theme-system.js";

test("고정 게임 제목이 두 HTML의 title·meta·화면에 존재한다",async()=>{for(const file of["index.html","콩쥐야_줘때써.html"]){const html=await readFile(new URL(`../${file}`,import.meta.url),"utf8");assert.match(html,new RegExp(`<title>${GAME_TITLE}</title>`));assert.match(html,new RegExp(`content=\"${GAME_TITLE}`));assert.doesNotMatch(html,/콩쥐야, 좋됐어|교육과정상|교육과정에 따르면|교육과정 기준|교과 과정상/)}});
test("25개 모드의 장독대 색상과 두꺼비 테마가 고유하다",()=>{const themes=Object.values(JAR_THEMES);assert.equal(themes.length,25);assert.equal(new Set(themes.map(theme=>theme.jarColor)).size,25);assert.equal(new Set(themes.map(theme=>theme.toad)).size,25)});
test("화면용 모드 이름은 장독대 채우기 형식이다",()=>{assert.equal(displayJarName({title:"원자 번호 훈련"}),"원자 번호 장독대 채우기");assert.equal(displayJarName({title:"산화환원 판단"}),"산화환원 판단 장독대 채우기");assert.equal(displayJarName({title:"원자 번호 장독대 채우기"}),"원자 번호 장독대 채우기")});
test("대표 장독대 테마가 지정값과 일치한다",()=>{assert.equal(themeFor("atomic_number").jar,"bronze");assert.equal(themeFor("redox").toad,"split");assert.equal(themeFor("acid_base").pattern,"yin-yang")});
test("모바일 키패드는 descriptor 중심의 단일 컴포넌트다",async()=>{const code=await readFile(new URL("../assets/js/mobile-keypad.js",import.meta.url),"utf8");assert.match(code,/questionInput/);assert.match(code,/allowedKeys/);assert.match(code,/inputMode/);assert.match(code,/FORMULA_MODES/);assert.match(code,/mount\(\)/);assert.match(code,/destroy\(\)/);assert.doesNotMatch(code,/MutationObserver|setInterval/)});

test("모바일 정수 키패드는 삭제·전체 삭제·제출을 제공한다",async()=>{const code=await readFile(new URL("../assets/js/mobile-keypad.js",import.meta.url),"utf8");assert.match(code,/DIGITS\s*=\s*\["1",\s*"2",\s*"3",\s*"4",\s*"5",\s*"6",\s*"7",\s*"8",\s*"9",\s*"0"\]/);assert.match(code,/한 글자 지우기/);assert.match(code,/입력 전체 지우기/);assert.match(code,/정답 제출/);assert.match(code,/keypad-submit/)});
test("직접 게임 진입과 결과 화면에 로비 경로가 있다",async()=>{const code=await readFile(new URL("../assets/js/ui-effects.js",import.meta.url),"utf8");assert.match(code,/if\(!query&&!selection\?\.trainingId\)/);assert.match(code,/location\.replace\("index\.html"\)/);assert.match(code,/장독대 고르기로/)});
test("피버와 액션 연출 한글은 UTF-8 정상 문자열이다",async()=>{const code=await readFile(new URL("../assets/js/action-effects.js",import.meta.url),"utf8");for(const text of["깡!","시간 다 됐다!","왕두꺼비 등장!","황금 두꺼비 FEVER"]){assert.match(code,new RegExp(text))}assert.doesNotMatch(code,/繹|鸚|癒|룻닊|袁⑤|源놁/)});
test("모바일 최종 계약은 전용 레이아웃 파일에서 장면·문제·입력 도크·툴바를 관리한다",async()=>{const css=await readFile(new URL("../assets/css/mobile-game.css",import.meta.url),"utf8");assert.match(css,/--game-viewport-height/);assert.match(css,/grid-template-columns: minmax\(0, 1fr\)/);assert.match(css,/grid-template-rows: auto minmax\(154px, 34%\) minmax\(0, 1fr\)/);assert.match(css,/\.mobile-input-dock:not\(\[hidden\]\)/);assert.match(css,/\.game-bottom-toolbar/);assert.match(css,/safe-area-inset-bottom/)});
test("모바일 일시정지 툴바는 상태별 텍스트와 pressed 상태를 동기화한다",async()=>{const code=await readFile(new URL("../assets/js/ui-effects.js",import.meta.url),"utf8");assert.match(code,/const label=paused\?"계속하기":"일시정지"/);assert.match(code,/toolbarPause\.replaceChildren\(\)/);assert.match(code,/toolbarPause\.setAttribute\("aria-pressed",String\(paused\)\)/)});
